package lib

import "net/http"

// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

type PayLoadOneSignal struct {
	Body string `form:"body" json:"body"`
}

func SendMailGun() {
	req, err := http.NewRequest("GET", "https://api.mailgun.net/v3/sandboxd66b77f5ba444901bb36552b050bfffe.mailgun.org/messages", nil)
	if err != nil {
		// handle err
	}
	req.SetBasicAuth("api", "489fcff1493a0697aede15e0ac9ac61f-ba042922-2ed0ecfd")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		// handle err
	}
	defer resp.Body.Close()
}
