package lib

import "net/http"

// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

type PayLoadOneSignal struct {
	Body string `form:"body" json:"body"`
}

func SendMailGun() {
	req, err := http.NewRequest("GET", "https://api.mailgun.net/v3/sandbox620241f22f6b43f488ac2a9cdb451e40.mailgun.org/messages", nil)
	if err != nil {
		// handle err
	}
	req.SetBasicAuth("api", "8688e6703fabba9e49cb39098b8ae41a-ffefc4e4-bcc13685")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		// handle err
	}
	defer resp.Body.Close()
}
